### ISSUE TITLE
Need help on creating a uaac client

### ISSUE THREAD

**Issue by Akhilesh-Anb** [cloudfoundry-incubator/admin-ui#178]
Hi,

I'm trying to create a uaac client and its asking for redirect URI. Please help me on this

```
ubuntu@ip-10-0-0-16:~/akhilesh/admin-ui$ uaac client add admin_ui_client \
>  --authorities clients.write,cloud_controller.admin,cloud_controller.read,cloud_controller.write,doppler.firehose,openid,scim.read,scim.write,sps.write \
>  --authorized_grant_types authorization_code,client_credentials,refresh_token \
>  --autoapprove true \
>  --scope admin_ui.admin,admin_ui.user,openid \
>  -s admin_ui_secret

error response:
{
  "error": "invalid_client",
  "error_description": "authorization_code grant type requires at least one redirect URL."
}
ubuntu@ip-10-0-0-16:~/akhilesh/admin-ui$
```

Our cloud foundry is installed on AWS.

**Comment by rboykin** [comment]
@Akhilesh-Anb 

Given an IP where your admin ui is going to be installed, add the following clause to the uaac client add. I am assuming the admin ui is being his with http, not https here. I am also assuming the admin ui is exposing itself through port 8070.

--redirect_uri http://<IP of admin ui>:8070/login

I'll update the readme with this information.

**Comment by Akhilesh-Anb** [comment]
Thank you @rboykin for the quick reply on this.
I'll create uaac client with the redirect_uri and i'll update here if i face any issues.

Regards,
Akhilesh Appana

**Comment by rboykin** [comment]
Documented the addition of the redirect_uri to the README: https://github.com/cloudfoundry-incubator/admin-ui/commit/250137705504546cbb38706a105720c93a2a4dc4

**Comment by Akhilesh-Anb** [comment]
Hi @rboykin ,

i have created uaac client by providing the public DNS name in redirect_uri:

```
 scope: admin_ui.user openid admin_ui.admin
  client_id: admin_ui_client
  resource_ids: none
  authorized_grant_types: refresh_token client_credentials authorization_code
  redirect_uri: http://ec2-xx.xxx.xxx-x39.compute-1.amazonaws.com:8070/login
  autoapprove: true
  authorities: cloud_controller.read cloud_controller.write openid sps.write clients.write doppler.firehose scim.write
      scim.read cloud_controller.admin
  name: admin_ui_client
  required_user_groups:
  lastmodified: 1502088277000
  id: admin_ui_client

```

Now when i'm accessing the admin-UI using [http://ec2-xx.xxx.xxx-x39.compute-1.amazonaws.com:8070] in browser, I'm getting This site can’t be reached.

Attaching the log file.
[admin_ui.txt](https://github.com/cloudfoundry-incubator/admin-ui/files/1204088/admin_ui.txt)


Please help me on this.

Thanks,
Akhilesh Appana
